/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.ComboDataController;
const BaseModelDamageType = testerlib.BaseModelDamageType;
const InsuranceTypes = testerlib.InsuranceTypes;
const InsuranceCompanies = testerlib.InsuranceCompanies;

describe("ComboDataController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

});
