/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");
const baseController = require("../../lib/Controllers/BaseController");

const controller = testerlib.TrackingDamageController;
const BaseModelTrakingCode = testerlib.BaseModelTrakingCode;
const TrackingDamage = testerlib.TrackingDamage;
const TrackingDamageRequest = testerlib.TrackingDamageRequest;
const BaseModelStatusStatusCollections = testerlib.BaseModelStatusStatusCollections;
const BaseModelStatus = testerlib.BaseModelStatus;

describe("TrackingDamageController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

});
