/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.TravelInsuranceController;
const BaseModelTravelInsurance = testerlib.BaseModelTravelInsurance;

describe("TravelInsuranceController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

});
