/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of ElectronicEquipmentInsurancePolicyExtendView
 */
class ElectronicEquipmentInsurancePolicyExtendView extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.deviceTypeId = this.constructor.getValue(obj.deviceTypeId);
        this.deviceBrandId = this.constructor.getValue(obj.deviceBrandId);
        this.deviceModelId = this.constructor.getValue(obj.deviceModelId);
        this.deviceSerial = this.constructor.getValue(obj.deviceSerial);
        this.buildYear = this.constructor.getValue(obj.buildYear);
        this.deviceValue = this.constructor.getValue(obj.deviceValue);
        this.franchisee = this.constructor.getValue(obj.franchisee);
        this.hasWarranty = this.constructor.getValue(obj.hasWarranty);
        this.warrantyCompany = this.constructor.getValue(obj.warrantyCompany);
        this.serialInsuranceCard = this.constructor.getValue(obj.serialInsuranceCard);
        this.metaMediaBehindDeviceId = this.constructor.getValue(obj.metaMediaBehindDeviceId);
        this.metaMediaBehindDeviceUrl = this.constructor.getValue(obj.metaMediaBehindDeviceUrl);
        this.metaMediaOnDeviceId = this.constructor.getValue(obj.metaMediaOnDeviceId);
        this.metaMediaOnDeviceUrl = this.constructor.getValue(obj.metaMediaOnDeviceUrl);
        this.metaMediaDeviceBoxId = this.constructor.getValue(obj.metaMediaDeviceBoxId);
        this.metaMediaDeviceBoxUrl = this.constructor.getValue(obj.metaMediaDeviceBoxUrl);
        this.insuranceCoverageIds =
          this.constructor.getValue(obj.insuranceCoverageIds
     || obj._InsuranceCoverageIds);
        this.insuranceCoveragePrice = this.constructor.getValue(obj.insuranceCoveragePrice);
        this.basePremium = this.constructor.getValue(obj.basePremium);
        this.allPremium = this.constructor.getValue(obj.allPremium);
        this.insuranceCompanyDiscountRate =
          this.constructor.getValue(obj.insuranceCompanyDiscountRate);
        this.insuranceCompanyDiscount = this.constructor.getValue(obj.insuranceCompanyDiscount);
        this.insuranceCentreDiscount = this.constructor.getValue(obj.insuranceCentreDiscount);
        this.coupenDiscount = this.constructor.getValue(obj.coupenDiscount);
        this.allDiscount = this.constructor.getValue(obj.allDiscount);
        this.exchangePremium = this.constructor.getValue(obj.exchangePremium);
        this.deviceTypeTitle = this.constructor.getValue(obj.deviceTypeTitle);
        this.deviceBrandTitle = this.constructor.getValue(obj.deviceBrandTitle);
        this.deviceModelTitle = this.constructor.getValue(obj.deviceModelTitle);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'deviceTypeId', realName: 'deviceTypeId' },
            { name: 'deviceBrandId', realName: 'deviceBrandId' },
            { name: 'deviceModelId', realName: 'deviceModelId' },
            { name: 'deviceSerial', realName: 'deviceSerial' },
            { name: 'buildYear', realName: 'buildYear' },
            { name: 'deviceValue', realName: 'deviceValue' },
            { name: 'franchisee', realName: 'franchisee' },
            { name: 'hasWarranty', realName: 'hasWarranty' },
            { name: 'warrantyCompany', realName: 'warrantyCompany' },
            { name: 'serialInsuranceCard', realName: 'serialInsuranceCard' },
            { name: 'metaMediaBehindDeviceId', realName: 'metaMediaBehindDeviceId' },
            { name: 'metaMediaBehindDeviceUrl', realName: 'metaMediaBehindDeviceUrl' },
            { name: 'metaMediaOnDeviceId', realName: 'metaMediaOnDeviceId' },
            { name: 'metaMediaOnDeviceUrl', realName: 'metaMediaOnDeviceUrl' },
            { name: 'metaMediaDeviceBoxId', realName: 'metaMediaDeviceBoxId' },
            { name: 'metaMediaDeviceBoxUrl', realName: 'metaMediaDeviceBoxUrl' },
            { name: 'insuranceCoverageIds', realName: '_InsuranceCoverageIds' },
            { name: 'insuranceCoveragePrice', realName: 'insuranceCoveragePrice' },
            { name: 'basePremium', realName: 'basePremium' },
            { name: 'allPremium', realName: 'allPremium' },
            { name: 'insuranceCompanyDiscountRate', realName: 'insuranceCompanyDiscountRate' },
            { name: 'insuranceCompanyDiscount', realName: 'insuranceCompanyDiscount' },
            { name: 'insuranceCentreDiscount', realName: 'insuranceCentreDiscount' },
            { name: 'coupenDiscount', realName: 'coupenDiscount' },
            { name: 'allDiscount', realName: 'allDiscount' },
            { name: 'exchangePremium', realName: 'exchangePremium' },
            { name: 'deviceTypeTitle', realName: 'deviceTypeTitle' },
            { name: 'deviceBrandTitle', realName: 'deviceBrandTitle' },
            { name: 'deviceModelTitle', realName: 'deviceModelTitle' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = ElectronicEquipmentInsurancePolicyExtendView;
