/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of ElevatorInsurancePolicyFilter
 */
class ElevatorInsurancePolicyFilter extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.buildingUseTypeParamId = this.constructor.getValue(obj.buildingUseTypeParamId);
        this.elevatorTypeParamId = this.constructor.getValue(obj.elevatorTypeParamId);
        this.floors = this.constructor.getValue(obj.floors);
        this.elevatorCapacityCargo = this.constructor.getValue(obj.elevatorCapacityCargo);
        this.elevatorCapacity = this.constructor.getValue(obj.elevatorCapacity);
        this.riskLevelId = this.constructor.getValue(obj.riskLevelId);
        this.insurancePolicyTerms = this.constructor.getValue(obj.insurancePolicyTerms);
        this.defectOrganCoverageId = this.constructor.getValue(obj.defectOrganCoverageId);
        this.deathCapitalCoverageId = this.constructor.getValue(obj.deathCapitalCoverageId);
        this.financialCoverageId = this.constructor.getValue(obj.financialCoverageId);
        this.medicalCostCoverageId = this.constructor.getValue(obj.medicalCostCoverageId);
        this.ownerCoverage = this.constructor.getValue(obj.ownerCoverage);
        this.insuranceExtraCoverageIds = this.constructor.getValue(obj.insuranceExtraCoverageIds);
        this.policyTermId = this.constructor.getValue(obj.policyTermId);
        this.insuranceCentreSubDomainName =
          this.constructor.getValue(obj.insuranceCentreSubDomainName);
        this.insuranceCentreId = this.constructor.getValue(obj.insuranceCentreId);
        this.insuranceCompanyId = this.constructor.getValue(obj.insuranceCompanyId);
        this.isSearchQuery = this.constructor.getValue(obj.isSearchQuery);
        this.giftCode = this.constructor.getValue(obj.giftCode);
        this.customerUserId = this.constructor.getValue(obj.customerUserId);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'buildingUseTypeParamId', realName: 'buildingUseTypeParamId' },
            { name: 'elevatorTypeParamId', realName: 'elevatorTypeParamId' },
            { name: 'floors', realName: 'floors' },
            { name: 'elevatorCapacityCargo', realName: 'elevatorCapacityCargo' },
            { name: 'elevatorCapacity', realName: 'elevatorCapacity' },
            { name: 'riskLevelId', realName: 'riskLevelId' },
            { name: 'insurancePolicyTerms', realName: 'insurancePolicyTerms' },
            { name: 'defectOrganCoverageId', realName: 'defectOrganCoverageId' },
            { name: 'deathCapitalCoverageId', realName: 'deathCapitalCoverageId' },
            { name: 'financialCoverageId', realName: 'financialCoverageId' },
            { name: 'medicalCostCoverageId', realName: 'medicalCostCoverageId' },
            { name: 'ownerCoverage', realName: 'ownerCoverage' },
            { name: 'insuranceExtraCoverageIds', realName: 'insuranceExtraCoverageIds' },
            { name: 'policyTermId', realName: 'policyTermId' },
            { name: 'insuranceCentreSubDomainName', realName: 'insuranceCentreSubDomainName' },
            { name: 'insuranceCentreId', realName: 'insuranceCentreId' },
            { name: 'insuranceCompanyId', realName: 'insuranceCompanyId' },
            { name: 'isSearchQuery', realName: 'isSearchQuery' },
            { name: 'giftCode', realName: 'giftCode' },
            { name: 'customerUserId', realName: 'customerUserId' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = ElevatorInsurancePolicyFilter;
