/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of ElevatorInsurance
 */
class ElevatorInsurance extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.hasPlan = this.constructor.getValue(obj.hasPlan);
        this.buildingUseTypes = this.constructor.getValue(obj.buildingUseTypes);
        this.elevatorTypes = this.constructor.getValue(obj.elevatorTypes);
        this.defectOrganCoverage = this.constructor.getValue(obj.defectOrganCoverage);
        this.deathCapitalCoverage = this.constructor.getValue(obj.deathCapitalCoverage);
        this.financialCoverage = this.constructor.getValue(obj.financialCoverage);
        this.medicalCostCoverage = this.constructor.getValue(obj.medicalCostCoverage);
        this.insuranceRiskLevels = this.constructor.getValue(obj.insuranceRiskLevels);
        this.insurancePolicyTerms = this.constructor.getValue(obj.insurancePolicyTerms);
        this.insuranceCompanies = this.constructor.getValue(obj.insuranceCompanies);
        this.provinces = this.constructor.getValue(obj.provinces);
        this.cities = this.constructor.getValue(obj.cities);
        this.cityRegions = this.constructor.getValue(obj.cityRegions);
        this.shippingTypes = this.constructor.getValue(obj.shippingTypes);
        this.postTypes = this.constructor.getValue(obj.postTypes);
        this.insurancePolicyCondition = this.constructor.getValue(obj.insurancePolicyCondition);
        this.insuranceData = this.constructor.getValue(obj.insuranceData);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'hasPlan', realName: 'hasPlan' },
            {
                name: 'buildingUseTypes',
                realName: 'buildingUseTypes',
                array: true,
                type: 'ComboDataModel',
            },
            { name: 'elevatorTypes', realName: 'elevatorTypes', array: true, type: 'ElevatorType' },
            {
                name: 'defectOrganCoverage',
                realName: 'defectOrganCoverage',
                array: true,
                type: 'DefectOrganCoverage',
            },
            {
                name: 'deathCapitalCoverage',
                realName: 'deathCapitalCoverage',
                array: true,
                type: 'DeathCapitalCoverage',
            },
            {
                name: 'financialCoverage',
                realName: 'financialCoverage',
                array: true,
                type: 'FinancialCoverage',
            },
            {
                name: 'medicalCostCoverage',
                realName: 'medicalCostCoverage',
                array: true,
                type: 'MedicalCostCoverage',
            },
            {
                name: 'insuranceRiskLevels',
                realName: 'insuranceRiskLevels',
                array: true,
                type: 'InsuranceRiskLevel',
            },
            {
                name: 'insurancePolicyTerms',
                realName: 'insurancePolicyTerms',
                array: true,
                type: 'InsurancePolicyTerm',
            },
            {
                name: 'insuranceCompanies',
                realName: 'insuranceCompanies',
                array: true,
                type: 'InsuranceCompany',
            },
            { name: 'provinces', realName: 'provinces', array: true, type: 'Province' },
            { name: 'cities', realName: 'cities', array: true },
            { name: 'cityRegions', realName: 'cityRegions', array: true },
            { name: 'shippingTypes', realName: 'shippingTypes', array: true, type: 'ShippingType' },
            { name: 'postTypes', realName: 'postTypes', array: true, type: 'PostType' },
            {
                name: 'insurancePolicyCondition',
                realName: 'insurancePolicyCondition',
                type: 'InsurancePolicyCondition',
            },
            {
                name: 'insuranceData',
                realName: 'insuranceData',
                type: 'InsuranceDataElevatorInsurance',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = ElevatorInsurance;
