/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of FaqInsuranceCentre
 */
class FaqInsuranceCentre extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.insuranceCentreId = this.constructor.getValue(obj.insuranceCentreId);
        this.question = this.constructor.getValue(obj.question);
        this.answer = this.constructor.getValue(obj.answer);
        this.sortPriority = this.constructor.getValue(obj.sortPriority);
        this.questionGroupParamId = this.constructor.getValue(obj.questionGroupParamId);
        this.isActive = this.constructor.getValue(obj.isActive);
        this.theInsuranceCentre = this.constructor.getValue(obj.theInsuranceCentre);
        this.theQuestionGroupParam = this.constructor.getValue(obj.theQuestionGroupParam);
        this.createOn = this.constructor.getValue(obj.createOn);
        this.updateOn = this.constructor.getValue(obj.updateOn);
        this.createdBy = this.constructor.getValue(obj.createdBy);
        this.updatedBy = this.constructor.getValue(obj.updatedBy);
        this.createOnPersianDate = this.constructor.getValue(obj.createOnPersianDate);
        this.updateOnPersianDate = this.constructor.getValue(obj.updateOnPersianDate);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'insuranceCentreId', realName: 'insuranceCentreId' },
            { name: 'question', realName: 'question' },
            { name: 'answer', realName: 'answer' },
            { name: 'sortPriority', realName: 'sortPriority' },
            { name: 'questionGroupParamId', realName: 'questionGroupParamId' },
            { name: 'isActive', realName: 'isActive' },
            { name: 'theInsuranceCentre', realName: 'theInsuranceCentre' },
            { name: 'theQuestionGroupParam', realName: 'theQuestionGroupParam' },
            { name: 'createOn', realName: 'createOn' },
            { name: 'updateOn', realName: 'updateOn' },
            { name: 'createdBy', realName: 'createdBy' },
            { name: 'updatedBy', realName: 'updatedBy' },
            { name: 'createOnPersianDate', realName: 'createOnPersianDate' },
            { name: 'updateOnPersianDate', realName: 'updateOnPersianDate' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = FaqInsuranceCentre;
