/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of FireInsurancePolicyFilter
 */
class FireInsurancePolicyFilter extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.insurancePolicyType = this.constructor.getValue(obj.insurancePolicyType);
        this.insuranceExtraCoverageIds = this.constructor.getValue(obj.insuranceExtraCoverageIds);
        this.valuePerSquareMeterCoverageRateId =
          this.constructor.getValue(obj.valuePerSquareMeterCoverageRateId);
        this.valueOfAppliancesFurnishing =
          this.constructor.getValue(obj.valueOfAppliancesFurnishing);
        this.cityId = this.constructor.getValue(obj.cityId);
        this.skeletonTypeId = this.constructor.getValue(obj.skeletonTypeId);
        this.buildingTypeId = this.constructor.getValue(obj.buildingTypeId);
        this.buildingArea = this.constructor.getValue(obj.buildingArea);
        this.onlyAppliancesFurnishings = this.constructor.getValue(obj.onlyAppliancesFurnishings);
        this.policyTermId = this.constructor.getValue(obj.policyTermId);
        this.insuranceCentreSubDomainName =
          this.constructor.getValue(obj.insuranceCentreSubDomainName);
        this.insuranceCentreId = this.constructor.getValue(obj.insuranceCentreId);
        this.insuranceCompanyId = this.constructor.getValue(obj.insuranceCompanyId);
        this.giftCode = this.constructor.getValue(obj.giftCode);
        this.customerUserId = this.constructor.getValue(obj.customerUserId);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'insurancePolicyType', realName: 'insurancePolicyType' },
            { name: 'insuranceExtraCoverageIds', realName: 'insuranceExtraCoverageIds' },
            {
                name: 'valuePerSquareMeterCoverageRateId',
                realName: 'valuePerSquareMeterCoverageRateId',
            },
            { name: 'valueOfAppliancesFurnishing', realName: 'valueOfAppliancesFurnishing' },
            { name: 'cityId', realName: 'cityId' },
            { name: 'skeletonTypeId', realName: 'skeletonTypeId' },
            { name: 'buildingTypeId', realName: 'buildingTypeId' },
            { name: 'buildingArea', realName: 'buildingArea' },
            { name: 'onlyAppliancesFurnishings', realName: 'onlyAppliancesFurnishings' },
            { name: 'policyTermId', realName: 'policyTermId' },
            { name: 'insuranceCentreSubDomainName', realName: 'insuranceCentreSubDomainName' },
            { name: 'insuranceCentreId', realName: 'insuranceCentreId' },
            { name: 'insuranceCompanyId', realName: 'insuranceCompanyId' },
            { name: 'giftCode', realName: 'giftCode' },
            { name: 'customerUserId', realName: 'customerUserId' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = FireInsurancePolicyFilter;
