/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of GalleryDetail
 */
class GalleryDetail extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.galleryId = this.constructor.getValue(obj.galleryId);
        this.metaMediaFileId = this.constructor.getValue(obj.metaMediaFileId);
        this.metaMediaFileUrl = this.constructor.getValue(obj.metaMediaFileUrl);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'galleryId', realName: 'galleryId' },
            { name: 'metaMediaFileId', realName: 'metaMediaFileId' },
            { name: 'metaMediaFileUrl', realName: 'metaMediaFileUrl' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = GalleryDetail;
