/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of InsurancePolicyTracking
 */
class InsurancePolicyTracking extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.aliasName = this.constructor.getValue(obj.aliasName);
        this.status = this.constructor.getValue(obj.status);
        this.createOnPersianDate = this.constructor.getValue(obj.createOnPersianDate);
        this.centerName = this.constructor.getValue(obj.centerName);
        this.insurancePolicyType = this.constructor.getValue(obj.insurancePolicyType);
        this.insuranceType = this.constructor.getValue(obj.insuranceType);
        this.price = this.constructor.getValue(obj.price);
        this.paymented = this.constructor.getValue(obj.paymented);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'aliasName', realName: 'aliasName' },
            { name: 'status', realName: 'status' },
            { name: 'createOnPersianDate', realName: 'createOnPersianDate' },
            { name: 'centerName', realName: 'centerName' },
            { name: 'insurancePolicyType', realName: 'insurancePolicyType' },
            { name: 'insuranceType', realName: 'insuranceType' },
            { name: 'price', realName: 'price' },
            { name: 'paymented', realName: 'paymented' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = InsurancePolicyTracking;
