/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of LiabilityDoctorInsurance
 */
class LiabilityDoctorInsurance extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.hasPlan = this.constructor.getValue(obj.hasPlan);
        this.activityArea = this.constructor.getValue(obj.activityArea);
        this.expertises = this.constructor.getValue(obj.expertises);
        this.commitmentCeilings = this.constructor.getValue(obj.commitmentCeilings);
        this.physicalCommitment = this.constructor.getValue(obj.physicalCommitment);
        this.insuranceCompanies = this.constructor.getValue(obj.insuranceCompanies);
        this.insuranceRiskLevels = this.constructor.getValue(obj.insuranceRiskLevels);
        this.insurancePolicyTerms = this.constructor.getValue(obj.insurancePolicyTerms);
        this.provinces = this.constructor.getValue(obj.provinces);
        this.cities = this.constructor.getValue(obj.cities);
        this.cityRegions = this.constructor.getValue(obj.cityRegions);
        this.shippingTypes = this.constructor.getValue(obj.shippingTypes);
        this.postTypes = this.constructor.getValue(obj.postTypes);
        this.insurancePolicyCondition = this.constructor.getValue(obj.insurancePolicyCondition);
        this.insuranceData = this.constructor.getValue(obj.insuranceData);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'hasPlan', realName: 'hasPlan' },
            { name: 'activityArea', realName: 'activityArea', array: true, type: 'ActivityArea' },
            { name: 'expertises', realName: 'expertises', array: true, type: 'Expertise' },
            {
                name: 'commitmentCeilings',
                realName: 'commitmentCeilings',
                array: true,
                type: 'CommitmentCeiling',
            },
            { name: 'physicalCommitment', realName: 'physicalCommitment' },
            {
                name: 'insuranceCompanies',
                realName: 'insuranceCompanies',
                array: true,
                type: 'InsuranceCompany',
            },
            {
                name: 'insuranceRiskLevels',
                realName: 'insuranceRiskLevels',
                array: true,
                type: 'InsuranceRiskLevel',
            },
            {
                name: 'insurancePolicyTerms',
                realName: 'insurancePolicyTerms',
                array: true,
                type: 'InsurancePolicyTerm',
            },
            { name: 'provinces', realName: 'provinces', array: true, type: 'Province' },
            { name: 'cities', realName: 'cities', array: true },
            { name: 'cityRegions', realName: 'cityRegions', array: true },
            { name: 'shippingTypes', realName: 'shippingTypes', array: true, type: 'ShippingType' },
            { name: 'postTypes', realName: 'postTypes', array: true, type: 'PostType' },
            {
                name: 'insurancePolicyCondition',
                realName: 'insurancePolicyCondition',
                type: 'InsurancePolicyCondition',
            },
            {
                name: 'insuranceData',
                realName: 'insuranceData',
                type: 'InsuranceDataLiabilityDoctorInsurance',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = LiabilityDoctorInsurance;
