/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of PopupImageGalleryie
 */
class PopupImageGalleryie extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.cached = this.constructor.getValue(obj.cached || obj._cached);
        this.url = this.constructor.getValue(obj.url);
        this.thumbnailUrl = this.constructor.getValue(obj.thumbnailUrl);
        this.altText = this.constructor.getValue(obj.altText);
        this.title = this.constructor.getValue(obj.title);
        this.extUrl = this.constructor.getValue(obj.extUrl);
        this.extUrlTarget = this.constructor.getValue(obj.extUrlTarget);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'cached', realName: '_cached' },
            { name: 'url', realName: 'url' },
            { name: 'thumbnailUrl', realName: 'thumbnailUrl' },
            { name: 'altText', realName: 'altText' },
            { name: 'title', realName: 'title' },
            { name: 'extUrl', realName: 'extUrl' },
            { name: 'extUrlTarget', realName: 'extUrlTarget' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = PopupImageGalleryie;
