/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of PortalLandingPage
 */
class PortalLandingPage extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.licensed = this.constructor.getValue(obj.licensed);
        this.insuranceGroup = this.constructor.getValue(obj.insuranceGroup);
        this.insuranceType = this.constructor.getValue(obj.insuranceType);
        this.summaryCards = this.constructor.getValue(obj.summaryCards);
        this.summaryNotics = this.constructor.getValue(obj.summaryNotics);
        this.imageAlbums = this.constructor.getValue(obj.imageAlbums);
        this.videoGalleries = this.constructor.getValue(obj.videoGalleries);
        this.insuranceCentre = this.constructor.getValue(obj.insuranceCentre);
        this.insuranceCentrePortal = this.constructor.getValue(obj.insuranceCentrePortal);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'licensed', realName: 'licensed' },
            {
                name: 'insuranceGroup',
                realName: 'insuranceGroup',
                array: true,
                type: 'InsuranceGroup',
            },
            { name: 'insuranceType', realName: 'insuranceType', array: true },
            { name: 'summaryCards', realName: 'summaryCards', array: true, type: 'SummaryCard' },
            { name: 'summaryNotics', realName: 'summaryNotics', array: true, type: 'SummaryNotic' },
            { name: 'imageAlbums', realName: 'imageAlbums', array: true, type: 'ImageAlbum' },
            {
                name: 'videoGalleries',
                realName: 'videoGalleries',
                array: true,
                type: 'VideoGallery',
            },
            { name: 'insuranceCentre', realName: 'insuranceCentre', type: 'InsuranceCentre' },
            {
                name: 'insuranceCentrePortal',
                realName: 'insuranceCentrePortal',
                type: 'InsuranceCentrePortal',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = PortalLandingPage;
