/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Status
 */
class Status extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.entityId = this.constructor.getValue(obj.entityId);
        this.primaryEntityName = this.constructor.getValue(obj.primaryEntityName);
        this.statusCollectionId = this.constructor.getValue(obj.statusCollectionId);
        this.formData = this.constructor.getValue(obj.formData);
        this.statusTitle = this.constructor.getValue(obj.statusTitle);
        this.editable = this.constructor.getValue(obj.editable);
        this.statusCollectionParentId = this.constructor.getValue(obj.statusCollectionParentId);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'entityId', realName: 'entityId' },
            { name: 'primaryEntityName', realName: 'primaryEntityName' },
            { name: 'statusCollectionId', realName: 'statusCollectionId' },
            { name: 'formData', realName: 'formData' },
            { name: 'statusTitle', realName: 'statusTitle' },
            { name: 'editable', realName: 'editable' },
            { name: 'statusCollectionParentId', realName: 'statusCollectionParentId' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Status;
