/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of StatusStatusCollections
 */
class StatusStatusCollections extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.parentId = this.constructor.getValue(obj.parentId);
        this.statusType = this.constructor.getValue(obj.statusType);
        this.title = this.constructor.getValue(obj.title);
        this.iconName = this.constructor.getValue(obj.iconName);
        this.description = this.constructor.getValue(obj.description);
        this.editable = this.constructor.getValue(obj.editable);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'parentId', realName: 'parentId' },
            { name: 'statusType', realName: 'statusType' },
            { name: 'title', realName: 'title' },
            { name: 'iconName', realName: 'iconName' },
            { name: 'description', realName: 'description' },
            { name: 'editable', realName: 'editable' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = StatusStatusCollections;
