/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of SummaryCard
 */
class SummaryCard extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.insuranceCentreId = this.constructor.getValue(obj.insuranceCentreId);
        this.articleType = this.constructor.getValue(obj.articleType);
        this.title = this.constructor.getValue(obj.title);
        this.summary = this.constructor.getValue(obj.summary);
        this.articleGroup = this.constructor.getValue(obj.articleGroup);
        this.metaMediaFileId = this.constructor.getValue(obj.metaMediaFileId);
        this.metaMediaFileUrl = this.constructor.getValue(obj.metaMediaFileUrl);
        this.publishPersianDate = this.constructor.getValue(obj.publishPersianDate);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'insuranceCentreId', realName: 'insuranceCentreId' },
            { name: 'articleType', realName: 'articleType' },
            { name: 'title', realName: 'title' },
            { name: 'summary', realName: 'summary' },
            { name: 'articleGroup', realName: 'articleGroup' },
            { name: 'metaMediaFileId', realName: 'metaMediaFileId' },
            { name: 'metaMediaFileUrl', realName: 'metaMediaFileUrl' },
            { name: 'publishPersianDate', realName: 'publishPersianDate' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = SummaryCard;
