/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of TrackingCode
 */
class TrackingCode extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.insuranceTypeId = this.constructor.getValue(obj.insuranceTypeId);
        this.insuranceCentreId = this.constructor.getValue(obj.insuranceCentreId);
        this.insuranceCentreName = this.constructor.getValue(obj.insuranceCentreName);
        this.insuranceCompanyId = this.constructor.getValue(obj.insuranceCompanyId);
        this.insuranceCompanyTitle = this.constructor.getValue(obj.insuranceCompanyTitle);
        this.insurancePolicyNumber = this.constructor.getValue(obj.insurancePolicyNumber);
        this.personalityType = this.constructor.getValue(obj.personalityType);
        this.damageType = this.constructor.getValue(obj.damageType);
        this.name = this.constructor.getValue(obj.name);
        this.nationalCode = this.constructor.getValue(obj.nationalCode);
        this.mobile = this.constructor.getValue(obj.mobile);
        this.insuredProfile = this.constructor.getValue(obj.insuredProfile);
        this.refrencedUser = this.constructor.getValue(obj.refrencedUser);
        this.referenceCount = this.constructor.getValue(obj.referenceCount);
        this.trackingCode = this.constructor.getValue(obj.trackingCode);
        this.paymentType = this.constructor.getValue(obj.paymentType);
        this.paymentDate = this.constructor.getValue(obj.paymentDate);
        this.paymentPersianDate = this.constructor.getValue(obj.paymentPersianDate);
        this.subDomain = this.constructor.getValue(obj.subDomain);
        this.insuranceTypeTitle = this.constructor.getValue(obj.insuranceTypeTitle);
        this.createOn = this.constructor.getValue(obj.createOn);
        this.updateOn = this.constructor.getValue(obj.updateOn);
        this.createOnPersianDate = this.constructor.getValue(obj.createOnPersianDate);
        this.updateOnPersianDate = this.constructor.getValue(obj.updateOnPersianDate);
        this.trackingDamageStatus = this.constructor.getValue(obj.trackingDamageStatus);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'insuranceTypeId', realName: 'insuranceTypeId' },
            { name: 'insuranceCentreId', realName: 'insuranceCentreId' },
            { name: 'insuranceCentreName', realName: 'insuranceCentreName' },
            { name: 'insuranceCompanyId', realName: 'insuranceCompanyId' },
            { name: 'insuranceCompanyTitle', realName: 'insuranceCompanyTitle' },
            { name: 'insurancePolicyNumber', realName: 'insurancePolicyNumber' },
            { name: 'personalityType', realName: 'personalityType' },
            { name: 'damageType', realName: 'damageType' },
            { name: 'name', realName: 'name' },
            { name: 'nationalCode', realName: 'nationalCode' },
            { name: 'mobile', realName: 'mobile' },
            { name: 'insuredProfile', realName: 'insuredProfile' },
            { name: 'refrencedUser', realName: 'refrencedUser' },
            { name: 'referenceCount', realName: 'referenceCount' },
            { name: 'trackingCode', realName: 'trackingCode' },
            { name: 'paymentType', realName: 'paymentType' },
            { name: 'paymentDate', realName: 'paymentDate' },
            { name: 'paymentPersianDate', realName: 'paymentPersianDate' },
            { name: 'subDomain', realName: 'subDomain' },
            { name: 'insuranceTypeTitle', realName: 'insuranceTypeTitle' },
            { name: 'createOn', realName: 'createOn' },
            { name: 'updateOn', realName: 'updateOn' },
            { name: 'createOnPersianDate', realName: 'createOnPersianDate' },
            { name: 'updateOnPersianDate', realName: 'updateOnPersianDate' },
            {
                name: 'trackingDamageStatus',
                realName: 'trackingDamageStatus',
                array: true,
                type: 'TrackingDamageStatusTrackingCode',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = TrackingCode;
