/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of TrackingDamageRequest
 */
class TrackingDamageRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.personalityType = this.constructor.getValue(obj.personalityType);
        this.trackingDamageStatus = this.constructor.getValue(obj.trackingDamageStatus);
        this.description = this.constructor.getValue(obj.description);
        this.insuranceTypeId = this.constructor.getValue(obj.insuranceTypeId);
        this.insuranceCompanyId = this.constructor.getValue(obj.insuranceCompanyId);
        this.insurancePolicyNumber = this.constructor.getValue(obj.insurancePolicyNumber);
        this.damageType = this.constructor.getValue(obj.damageType);
        this.name = this.constructor.getValue(obj.name);
        this.nationalCode = this.constructor.getValue(obj.nationalCode);
        this.mobile = this.constructor.getValue(obj.mobile);
        this.insuredProfile = this.constructor.getValue(obj.insuredProfile);
        this.subDomain = this.constructor.getValue(obj.subDomain);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'personalityType', realName: 'personalityType' },
            {
                name: 'trackingDamageStatus',
                realName: 'trackingDamageStatus',
                array: true,
                type: 'TrackingDamageStatus',
            },
            { name: 'description', realName: 'description' },
            { name: 'insuranceTypeId', realName: 'insuranceTypeId' },
            { name: 'insuranceCompanyId', realName: 'insuranceCompanyId' },
            { name: 'insurancePolicyNumber', realName: 'insurancePolicyNumber' },
            { name: 'damageType', realName: 'damageType' },
            { name: 'name', realName: 'name' },
            { name: 'nationalCode', realName: 'nationalCode' },
            { name: 'mobile', realName: 'mobile' },
            { name: 'insuredProfile', realName: 'insuredProfile' },
            { name: 'subDomain', realName: 'subDomain' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = TrackingDamageRequest;
