/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of TrackingDamageStatusTrackingCode
 */
class TrackingDamageStatusTrackingCode extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.trackingDamageId = this.constructor.getValue(obj.trackingDamageId);
        this.description = this.constructor.getValue(obj.description);
        this.trackingDamageStatus = this.constructor.getValue(obj.trackingDamageStatus);
        this.trackingDamageFile = this.constructor.getValue(obj.trackingDamageFile);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'trackingDamageId', realName: 'trackingDamageId' },
            { name: 'description', realName: 'description' },
            { name: 'trackingDamageStatus', realName: 'trackingDamageStatus' },
            {
                name: 'trackingDamageFile',
                realName: 'trackingDamageFile',
                array: true,
                type: 'TrackingDamageFileTrackinCode',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = TrackingDamageStatusTrackingCode;
