/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of TravelInsurance
 */
class TravelInsurance extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.hasPlan = this.constructor.getValue(obj.hasPlan);
        this.isSamanInsurance = this.constructor.getValue(obj.isSamanInsurance);
        this.zones = this.constructor.getValue(obj.zones);
        this.travelDurations = this.constructor.getValue(obj.travelDurations);
        this.travelAges = this.constructor.getValue(obj.travelAges);
        this.provinces = this.constructor.getValue(obj.provinces);
        this.cities = this.constructor.getValue(obj.cities);
        this.cityRegions = this.constructor.getValue(obj.cityRegions);
        this.shippingTypes = this.constructor.getValue(obj.shippingTypes);
        this.postTypes = this.constructor.getValue(obj.postTypes);
        this.insuranceData = this.constructor.getValue(obj.insuranceData);
        this.insurancePolicyCondition = this.constructor.getValue(obj.insurancePolicyCondition);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'hasPlan', realName: 'hasPlan' },
            { name: 'isSamanInsurance', realName: 'isSamanInsurance' },
            { name: 'zones', realName: 'zones', array: true, type: 'Zone' },
            {
                name: 'travelDurations',
                realName: 'travelDurations',
                array: true,
                type: 'TravelDuration',
            },
            { name: 'travelAges', realName: 'travelAges', array: true, type: 'TravelAge' },
            { name: 'provinces', realName: 'provinces', array: true, type: 'Province' },
            { name: 'cities', realName: 'cities', array: true },
            { name: 'cityRegions', realName: 'cityRegions', array: true },
            { name: 'shippingTypes', realName: 'shippingTypes', array: true, type: 'ShippingType' },
            { name: 'postTypes', realName: 'postTypes', array: true, type: 'PostType' },
            {
                name: 'insuranceData',
                realName: 'insuranceData',
                type: 'InsuranceDataTravelInsurance',
            },
            {
                name: 'insurancePolicyCondition',
                realName: 'insurancePolicyCondition',
                type: 'InsurancePolicyCondition',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = TravelInsurance;
