/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of TravelInsurancePolicyExtendView
 */
class TravelInsurancePolicyExtendView extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.travelInsurancePolicyExtend =
          this.constructor.getValue(obj.travelInsurancePolicyExtend);
        this.travelInsurancePolicyExtendAges =
          this.constructor.getValue(obj.travelInsurancePolicyExtendAges);
        this.travelInsurancePolicyExtendPassengers =
          this.constructor.getValue(obj.travelInsurancePolicyExtendPassengers);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            {
                name: 'travelInsurancePolicyExtend',
                realName: 'travelInsurancePolicyExtend',
                type: 'TravelInsurancePolicyExtend',
            },
            {
                name: 'travelInsurancePolicyExtendAges',
                realName: 'travelInsurancePolicyExtendAges',
                array: true,
            },
            {
                name: 'travelInsurancePolicyExtendPassengers',
                realName: 'travelInsurancePolicyExtendPassengers',
                array: true,
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = TravelInsurancePolicyExtendView;
